"""Add hypothesis and experiment models

Revision ID: 0003_hypothesis
Revises: 0002
Create Date: 2026-06-08 09:58:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_hypothesis"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hypotheses",
        sa.Column("hypothesis_id", sa.String(length=128), nullable=False),
        sa.Column("submission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("apk_sha256", sa.String(length=64), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("initial_confidence", sa.Float(), nullable=False),
        sa.Column("final_confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("unresolved_reason", sa.Text(), nullable=True),
        sa.Column("recommended_next_step", sa.Text(), nullable=True),
        sa.Column(
            "formed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expose_in_irt", sa.Boolean(), nullable=False),
        sa.Column("irt_label", sa.Text(), nullable=True),
        sa.Column("formed_by_agent", sa.String(length=64), nullable=False),
        sa.Column("spawned_from", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["spawned_from"], ["hypotheses.hypothesis_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("hypothesis_id"),
    )
    op.create_index(op.f("ix_hypotheses_submission_id"), "hypotheses", ["submission_id"], unique=False)
    op.create_index(op.f("ix_hypotheses_apk_sha256"), "hypotheses", ["apk_sha256"], unique=False)
    op.create_index(op.f("ix_hypotheses_status"), "hypotheses", ["status"], unique=False)

    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.String(length=128), nullable=False),
        sa.Column("hypothesis_id", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tool_used", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("evidence_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("failed_attempts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"], ["hypotheses.hypothesis_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_index(
        op.f("ix_experiments_hypothesis_id"), "experiments", ["hypothesis_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_experiments_hypothesis_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_hypotheses_status"), table_name="hypotheses")
    op.drop_index(op.f("ix_hypotheses_apk_sha256"), table_name="hypotheses")
    op.drop_index(op.f("ix_hypotheses_submission_id"), table_name="hypotheses")
    op.drop_table("hypotheses")
    # ### end Alembic commands ###
