"""add_observations_and_links

Revision ID: 0004_add_observations_and_links
Revises: 0003_hypothesis
Create Date: 2026-06-09 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004_add_observations_and_links"
down_revision: Union[str, None] = "0003_hypothesis"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("submission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=256), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("thread_name", sa.String(length=256), nullable=True),
        sa.Column("caller_package", sa.String(length=512), nullable=True),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("return_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exception", sa.Text(), nullable=True),
        sa.Column("captured_at_ms", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_observations_submission_id"), "observations", ["submission_id"], unique=False)

    op.create_table(
        "experiment_observation_links",
        sa.Column("hypothesis_id", sa.String(length=128), nullable=False),
        sa.Column("observation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"], ["hypotheses.hypothesis_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["observations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("hypothesis_id", "observation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("experiment_observation_links")
    op.drop_index(op.f("ix_observations_submission_id"), table_name="observations")
    op.drop_table("observations")
    # ### end Alembic commands ###
