import logging
import uuid
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from parallax.core.models import Hypothesis

logger = logging.getLogger(__name__)


class HypothesisEngine:
    """
    Responsible for initializing, tracking, and resolving hypotheses generated
    during the investigation loop.
    """

    def __init__(self, db: AsyncSession):
        self.db = db

    async def seed_initial_hypotheses(
        self, submission_id: uuid.UUID, sha256: str, triage_data: dict[str, Any]
    ) -> list[Hypothesis]:
        """
        Seeds the initial hypotheses generated by the Triage Agent into the database.
        """
        initial_hypotheses = triage_data.get("initial_hypotheses", [])
        created_records = []

        for item in initial_hypotheses:
            h = Hypothesis(
                hypothesis_id=f"HYP-{uuid.uuid4().hex[:8].upper()}",
                submission_id=submission_id,
                apk_sha256=sha256,
                claim=item.get("claim", "Unknown claim"),
                category=item.get("category", "static"),
                initial_confidence=float(item.get("initial_confidence", 0.0)),
                expose_in_irt=item.get("expose_in_irt", False),
                irt_label=item.get("irt_label", ""),
                status="PENDING",
                formed_by_agent="Triage Agent",
            )
            self.db.add(h)
            created_records.append(h)

        try:
            await self.db.commit()
            for record in created_records:
                await self.db.refresh(record)
            logger.info(f"Seeded {len(created_records)} initial hypotheses for {sha256}.")
        except Exception as e:
            await self.db.rollback()
            logger.error(f"Failed to seed hypotheses: {e}")
            raise

        return created_records

    async def process_static_results(
        self, submission_id: uuid.UUID, artifact: dict[str, Any]
    ) -> None:
        """
        Closes the loop between static analysis and the Hypothesis Engine.
        Evaluates the REArtifactModel dict and updates existing Hypotheses.
        """
        result = await self.db.execute(
            select(Hypothesis).where(Hypothesis.submission_id == submission_id)
        )
        hypotheses = result.scalars().all()
        if not hypotheses:
            return

        yara_matches = artifact.get("yara_matches", [])
        static_features = artifact.get("static_features", {})
        permissions = static_features.get("permissions", [])

        for h in hypotheses:
            claim_lower = h.claim.lower()

            # YARA Match loop closure
            if h.status != "CONFIRMED" and (
                "banking trojan" in claim_lower
                or "overlay" in claim_lower
                or "malware" in claim_lower
            ):
                for match in yara_matches:
                    rule_name = match.get("rule", "")
                    meta_category = match.get("meta", {}).get("category", "")

                    if (
                        rule_name.startswith("Android_BankingTrojan")
                        or meta_category == "Banking Trojan"
                    ):
                        h.status = "CONFIRMED"
                        h.status_reason = f"Confirmed by YARA rule: {rule_name}"
                        # A single match jumps to 0.95 because the YARA rule enforces 5+ indicator patterns (high specificity)
                        h.final_confidence = 0.95
                        break

            # Permission / Feature loop closure
            # Note: We only upgrade PENDING to INVESTIGATING. If already CONFIRMED (e.g. by YARA), we do not downgrade.
            if "sms" in claim_lower and any("RECEIVE_SMS" in p for p in permissions):
                if h.status == "PENDING":
                    h.status = "INVESTIGATING"
                    h.status_reason = "Static analysis found RECEIVE_SMS permission, warranting deeper dynamic test."

            if "accessibility" in claim_lower and any(
                "BIND_ACCESSIBILITY_SERVICE" in p for p in permissions
            ):
                if h.status == "PENDING":
                    h.status = "INVESTIGATING"
                    h.status_reason = "Static analysis found BIND_ACCESSIBILITY_SERVICE permission."

        try:
            await self.db.commit()
            logger.info(
                f"Processed static results for submission {submission_id}, updated hypotheses."
            )
        except Exception as e:
            await self.db.rollback()
            logger.error(f"Failed to update hypotheses with static results: {e}")
            raise
