import logging
import uuid
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from parallax.core.models import Hypothesis

logger = logging.getLogger(__name__)


class HypothesisEngine:
    """
    Responsible for initializing, tracking, and resolving hypotheses generated
    during the investigation loop.
    """

    def __init__(self, db: AsyncSession):
        self.db = db

    async def seed_initial_hypotheses(
        self, submission_id: str, sha256: str, triage_data: dict[str, Any]
    ) -> list[Hypothesis]:
        """
        Seeds the initial hypotheses generated by the Triage Agent into the database.
        """
        initial_hypotheses = triage_data.get("initial_hypotheses", [])
        created_records = []

        for item in initial_hypotheses:
            h = Hypothesis(
                hypothesis_id=f"HYP-{uuid.uuid4().hex[:8].upper()}",
                submission_id=submission_id,
                apk_sha256=sha256,
                claim=item.get("claim", "Unknown claim"),
                category=item.get("category", "static"),
                initial_confidence=float(item.get("initial_confidence", 0.0)),
                expose_in_irt=item.get("expose_in_irt", False),
                irt_label=item.get("irt_label", ""),
                status="PENDING",
                formed_by_agent="Triage Agent",
            )
            self.db.add(h)
            created_records.append(h)

        try:
            await self.db.commit()
            for record in created_records:
                await self.db.refresh(record)
            logger.info(f"Seeded {len(created_records)} initial hypotheses for {sha256}.")
        except Exception as e:
            await self.db.rollback()
            logger.error(f"Failed to seed hypotheses: {e}")
            raise

        return created_records
