{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parallax.secretName" . }}
  labels:
    {{- include "parallax.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
